env:
  global:
  - CC_TEST_REPORTER_ID=m1qjSGkw/9CseBq34lYR/3HLcW6K/8MA59MCcScYBFbsu8Sz0wS5I5Mnsohx5GD+G1dnsadFuKoR8LoF1OW7x24o7hUQMaVdaBg9Y5AUgSKTvzuxB4KP5oCluJfz9nCnWMe3pp/duJuvdnAKKcs/U9Bfzk7dUEgtIfxyKM8aUj6PRVTDDttLusWbZvnBrALamsSqXiwyRnOon4rA/Cm3zM6gyTxmqHllpjxNSsnmJUOU6fse2QFDzKkIVFoRBblDaOqczp87YvzDN79G6cjs9tkK1Nu7W+WrKZWHKdQSgmKoTo9dZFMU/MO1GjGNYZR1fhR+HYpxa1/zFdQ+dG7Lh+e1ScukSExrqACDJO7/AUiWPuAFICgr/rE1Nfdew/D2mvVg3leaejDB24tT7fCpWg60WOlbdGNYwvNyBHTYefugmaeBtqYZk/L8KKukOvoHzxNSipMdIdvQ3F9CGxXVL9gA5YgNMvvakDKKg2jvCdIPHfHYq79GzilFfU/yVa0f9EcbuJfxXza7dkL+LKV+O7YT7AMANzzuN9u2DKewF/b3G8K2tp7y5FMy6pCe/W9SfOJZjbb+2PFOYIDlrMLdhYb7TQYwZAD4JaPw809TJozWIEog99WxKlolb2+5EInim66xurASgexiwOWvhu3E/Cx0V/R4ZssCkvFi3RbkzTg=
language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
before_script:
- npm install
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- npm test
- npm run coveralls
- npm run codeClimate
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
